### ISSUE TITLE
use events for Marathon namer

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/linkerd#105]
The current Marathon namer polls the `/v2/apps` Marathon API endpoint:
https://github.com/BuoyantIO/linkerd/blob/master/marathon/src/main/scala/io/buoyant/marathon/v2/Api.scala

Using the Events API is a better solution:
https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-events

**Comment by adleong** [comment]
The marathon events api streams a non-chunked response using the Server-Sent Events format: https://www.w3.org/TR/eventsource/

This may be a problem for us because it seems finagle-http may not support non-chunked streaming.

**Comment by olix0r** [comment]
WONTFIX

**Comment by moderation** [comment]
You don't have to use SSE - there is a HTTP callback method - https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-eventsubscriptions
