### ISSUE TITLE
make delegator more explicitly handle connection failures from namers

### ISSUE THREAD

**Issue by esbie** [BuoyantIO/linkerd#112]
If you try to use the marathon namer while not running marathon, the namer throws a connection exception that isn't caught anywhere.

I think it should instead fail the lookup with NameTree.Neg or NameTree.Fail

**Comment by siggy** [comment]
We're making some changes to the marathon namer to more gracefully handle marathon availability changes, in https://github.com/BuoyantIO/linkerd/pull/164.

The marathon namer itself will continue to propagate `java.net.ConnectException` on first connection, if marathon is down.

Repurposing this ticket to make the Delegator more explicitly handle these conditions:
![marathon_503](https://cloud.githubusercontent.com/assets/236915/13797630/3b8f00f0-eacc-11e5-8b81-0a1afa44b6b7.png)

**Comment by olix0r** [comment]
Fixed by https://github.com/BuoyantIO/linkerd/pull/168 (right?)
