### ISSUE TITLE
Problems with stopping

### ISSUE THREAD

**Issue by likwid** [BuoyantIO/linkerd#117]
linkerd doesn't seem to daemonize properly. Maybe that isn't the right term, but when I execute ./linkerd start, I get a message that it has started. However, when I attempt to stop linkerd, it tells me it isn't running. 

```
ADMIN_PORT=$(grep -A1 '^admin:' config/linkerd.yaml | grep 'port:' | awk '{print ":" $2}') // :9990 by default
curl -s $ADMIN_PORT/admin/ping 
echo $?  // returns 6
```

Prepending localhost in the ADMIN_PORT assignment seems to fix the issue.
```
ADMIN_PORT=$(grep -A1 '^admin:' config/linkerd.yaml | grep 'port:' | awk '{print "localhost:" $2}')
```

**Comment by olix0r** [comment]
Thanks for reporting this!  That's a neat fix, but I think we're inclined to just remove the wrapper script in favor of platform-specific rc/init controllers.  I've opened https://github.com/BuoyantIO/linkerd/issues/118 to track that.

**Comment by olix0r** [comment]
In the most recent release, we removed the `linkerd` wrapper script in favor of an executable that simply runs in the foreground.
