### ISSUE TITLE
JavaScript error in admin ui

### ISSUE THREAD

**Issue by aclemmensen** [BuoyantIO/linkerd#119]
It appears there's a JS error in [`routers.js`](https://github.com/BuoyantIO/linkerd/blob/master/linkerd/admin/src/main/resources/io/buoyant/linkerd/admin/js/routers.js#L111).

Replacing `servers.find(` with `_.find(servers` fixes the issue.

Much of the admin UI appears broken without this fix.

**Comment by wmorgan** [comment]
Thanks for reporting this!

**Comment by gtcampbell** [comment]
@esbie points out that this is likely a browser-compatibility issue, as `Array.prototype.find` is [supported in newish Firefox/Chrome/Safari](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility) but not universal across browsers. We should switch to using the lodash-provided `_.find` for this function, and possibly consider using a runtime polyfill to help avoid this kind of issue in the future.
