### ISSUE TITLE
human-readable interface names on admin

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/linkerd#150]
The admin homepage displays verbose interface names such as:
`rt/outgoing/dst/id/io.l5d.k8s/prod/incoming/foo/requests`
Consider a way to render a more friendly version, for example:
`k8s/prod/foo`

**Comment by olix0r** [comment]
fwiw, i don't think it makes sense to be able to shorten "io.l5d.k8s" to k8s -- this is just some configured prefix name in a namer.  however, it would be very nice to be able to at least split apart _outgoing_ from _io.l5d.k8s/prod/incoming/foo/requests_

**Comment by rmars** [comment]
Would you say that this is fixed in the new dashboard?  Or do we still need some work on the naming?
