### ISSUE TITLE
make Probation configurable

### ISSUE THREAD

**Issue by olix0r** [BuoyantIO/linkerd#166]
Finagle's [LoadBalancerFactory.EnableProbation](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/loadbalancer/LoadBalancerFactory.scala#L28) param controls whether endpoints are eagerly evicted from service discovery.  we should add a configuration option to the router client config.

I also think we should enable this by default (i.e. in Router.scala).  It's a much safer default behavior that Twitter has not been able to change for legacy reasons.

**Comment by rmars** [comment]
Question - why enable it in Router.scala instead of putting a default value in LoadBalancerConfig.scala?

**Comment by olix0r** [comment]
There's no difference to the end user -- but really this is something that _should_ be a default in finagle.  If someone were to use the Router type directly as a library -- which is a reasonable expectation -- they should get this default behavior.
