### ISSUE TITLE
Issue with ForwardClientCert XFCC header when SAN contains types other than URI and DNS

### ISSUE THREAD

**Issue by shakti-das** [BuoyantIO/linkerd#1849]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
If certificate contains SAN entries other than DNS and URI then ForwardClientCertFilter will fail. 

**What you expected to happen**:
There shouldn't be any failure if SAN contains other types.

**How to reproduce it (as minimally and precisely as possible)**:
Adding IP SAN type in the openssl config in the tests will reproduce the issue.

**Anything else we need to know?**:
I worked on adding DNS SAN entries to XFCC, this issue was identified in our internal testing, have the fix ready, sending out a PR now.

**Environment**:
- linkerd/namerd version, config files: linkerd 1.3.6
- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:

**Comment by shakti-das** [comment]
@drichelson thanks for catching this issue.

**Comment by wmorgan** [comment]
@shakti-das @drichelson it's a pleasure working with you, as always
