### ISSUE TITLE
httpAccessLog on stdout/stderr?

### ISSUE THREAD

**Issue by benley** [BuoyantIO/linkerd#206]
Right now it's only possible to write httpAccessLogs to a file on disk.  It would be quite handy if linkerd could be configured to emit that on a stdout or stderr file descriptor.

**Comment by olix0r** [comment]
Is this perhaps just as simple as specifying /dev/std{out,err} in the destination file?

**Comment by benley** [comment]
it might be - I can test that and see if it works.  I seem to recall running into strange problems with using those in the past, but I don't remember what it was.

**Comment by endzyme** [comment]
Directing to `/dev/stdout` worked for me on docker container in the hub. +1

**Comment by olix0r** [comment]
thanks @endzyme.  closing this for now, but willing to reopen if it turns out that this doesn't work generically.
