### ISSUE TITLE
user-friendly namerd storage `kind`s

### ISSUE THREAD

**Issue by olix0r** [BuoyantIO/linkerd#308]
we currently use class names for our namerd storage kinds.  There's a bunch of redundant information in here.  Let's simplify these to "memory", "zookeeper", "kubernetes", ...

**Comment by adleong** [comment]
Can we decide on a project wide convention for how to name plugin kinds?  We're currently in a weird state where fully qualified class names are used in some places and not others, some kinds live in the `io.l5d` package while others live in the `io.buoyant` package.

**Comment by adleong** [comment]
https://docs.google.com/document/d/1_siXmv7mLrXlylFxzFWz3mtlJOwUdyrfS3tKgaCYrKQ/edit#
