### ISSUE TITLE
Namerd's http interfaces should each support both streaming and polling

### ISSUE THREAD

**Issue by adleong** [BuoyantIO/linkerd#309]
We should refactor our polling/stamping code so that we can have a principled way of doing streaming and polling on each API endpoint.

**Comment by gtcampbell** [comment]
are we talking about polling for changes since a particular timestamp, or just polling for the current state of the world?

**Comment by adleong** [comment]
Similar to how the thrift interface works.  I'd imagine you can poll with a version to get an update when that version is out-of-date, or you can poll without a version to get the current state immediately.

**Comment by olix0r** [comment]
Oh, the use case i had in mind was just simple non-streaming read -- not necessarily stamped polling (which sounds a bit more complex)
