### ISSUE TITLE
Investigate switching from synchronized maps to ConcurrentHashMap

### ISSUE THREAD

**Issue by adleong** [BuoyantIO/linkerd#310]
Namerd has a number of hand-rolled synchronized maps.  Investigate replacing these with ConcurrentHashMap or something similar.

**Comment by adleong** [comment]
Does anyone have opinions about using Guava cache for this?  Seems like a good fit since it's  thread-safe and also supports LRU semantics https://github.com/google/guava/wiki/CachesExplained

**Comment by olix0r** [comment]
Yeah, I think guava caches are promising.  Although, I think our desired caching semantics are not quite "LRU."  LRU will punish entries that are not updated frequently.  We want something closer to reference counted + LRU.

LRU could work if we, for instance, force an update on pending requests when the entry is being evicted so that clients have an opportunity to re-establish the watch...

**Comment by adleong** [comment]
I think the purpose of caching is different in the streaming world vs in the stamped polling world.

## Streaming ##
For streaming, the purpose of caching Activities is simply to make sure that multiple requests for the same name can share an Activity and to avoid unnecessarily re-creating Activity objects.  If an Activity gets kicked out of cache while there is an open request against it, that request will keep the Activity open even though it's no longer in the cache and the request will continue to get updates.  Also note that having an Activity in cache does not necessarily mean that the Activity is being observed so the only cost to keeping Activities in cache is the memory they take up.

For this scenario I think we should use a Guava cache with LRU or time based eviction.

Open question: how do we put a limit on the number of observed Activities?

## Stamped Polling ##
With stamped polling, on the other hand, caching also serves as a way to manage the observations.  If an observation is torn down while there are outstanding requests against it, those requests will hang forever.  Therefore, Observations need to be reference counted if we ever want to be able to tear them down.  I think in this case we actually want two caches:

* A ConcurrentHashMap called the "active" cache for observations with open requests against them as well as their reference counts.  When a request is received, the observation is looked up (in both caches) or created, it's moved to the active cache if it isn't already there, and the reference count is incremented.  When that observation's value changes, responses are sent, the reference count is set to 0, and the observation is moved to the inactive cache
* The inactive cache is a cache for observations that are not currently being observed.  This is similar to the cache in the streaming scenario in that it's purpose is just so that we don't have to recreate Activity objects.  This can be a guava cache with LRU or time based eviction.

By limiting the size of the active cache, we can limit the number of open observations and reject requests when that limit is reached.
