### ISSUE TITLE
remove namerd dependency on admin

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/linkerd#326]
motivated by this diff comment:
https://github.com/BuoyantIO/linkerd/pull/325#discussion-diff-60800260

... namerd's http interface and linkerd's admin both depend on delegator functionality that currently exists in the admin project. this delegator functionality should exist outside of either project, removing the dependency between the two.

Also, per https://github.com/BuoyantIO/linkerd/pull/325/files#r60811481, we need related utility functionality with `Activity.toFuture`, currently defined in `io.buoyant.namerd.RichActivity`.

**Comment by olix0r** [comment]
I think this is basically resolved, as we have separate packages for admin, linkerd-admin, and namerd-admin.
