### ISSUE TITLE
Support marathon master discovery via ZK

### ISSUE THREAD

**Issue by drewrobb** [BuoyantIO/linkerd#360]
In HA mode marathon stores the master(s) address in zk using a format very similar to server sets. While this isn't an officially supported format and could possibly change, it would be a nice feature for environments where a constant http address for marathon does not necessarily exist.

**Comment by olix0r** [comment]
good idea!

looks like marathon does twitter commons' leader election ([1](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/MarathonModule.scala#L262) [2](https://github.com/mesosphere/marathon/blob/master/src/main/java/mesosphere/marathon/core/leadership/CandidateImpl.java)) under [`/marathon/leader`](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/ZookeeperConf.scala) by default.

**Comment by drewrobb** [comment]
@olix0r would a reasonable solution be to make a class that implements `namer` for the twitter commons's leader election class? Then rather than modifying the marathon namer configuration options directly, one could just make a http router for marathon and then use that? something like:

```
namers:
- kind:      io.l5d.experimental.marathon
  prefix:    /marathon-test
  host: 127.0.0.1
  port: 11111

routers:
- protocol: http
  servers:
  - port: 11111
    ip: 0.0.0.0
  interpreter:
    kind: io.l5d.namerd
    dst: /$/some.new.class.extending.namer/zkhost:2181/marathon/leader
```

**Comment by olix0r** [comment]
That's a neat idea.  We could simply implement a _leader_ namer (there's nothing marathon-specific about it), and use that as a way to configure the marathon namer:

```yaml
namers:
- kind:      io.l5d.experimental.marathon
  dst: /$/io.l5d.zk.leader/zkhost:2181/marathon/leader
...
```

**Comment by drewrobb** [comment]
Thanks @adleong !
