### ISSUE TITLE
dashboard "metrics" link should just point to metrics.json

### ISSUE THREAD

**Issue by wmorgan** [BuoyantIO/linkerd#377]
Right now clicking on "metrics" points to the old metrics browser. I'd prefer we point it to /admin/metrics.json directly. The browser is not really in a usable state (e.g. almost every metric name is too long), isn't themed to match the dashboard, and I'd rather show off the programmatic endpoint than push people into that experience.

(Longer term we can consider whether we want to update the browser or discard it.)

**Comment by olix0r** [comment]
I'd be in favor of just removing the link.  Not sure how useful it is to get dumped to a huge inscrutable json blob
