### ISSUE TITLE
configurable admin url

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/linkerd#397]
it may be useful to configure admin to serve on a different url. for example, on DC/OS, admin can run at `dcos-url.com/service/linkerd`. today that page is broken because admin expects assets to be available under root, not under `/service/linkerd`.

this is similar to grafana's `root_url` flag: http://docs.grafana.org/installation/configuration/#root_url

**Comment by joerg84** [comment]
I guess it is sufficient to make the links relative to the current directory or?

**Comment by siggy** [comment]
@joerg84 correct, we can make the links relative. question for you: if we make this change, and the user can browse to `dcos-url.com/service/linkerd`, does that go to the public node, or does it load balance over all linkerd instances running in dc/os? if it's the latter, we'll need to rethink this, as the linkerd dashboard is designed to be a view of a single instance.

**Comment by joerg84** [comment]
@siggy your current implemention sets the labels for each linkerd task (See here mesosphere/universe/blob/version-3.x/repo/packages/L/linkerd/8/marathon.json.mustache#L42). Hence admin router will redirect to one of those tasks running (Not really loadbalanced). So it might serve from different instances. See also the my  last sentence on the original issue https://github.com/mesosphere/universe/issues/911

**Comment by joerg84** [comment]
FYI people can already browse there but they will see a broken site.
