### ISSUE TITLE
fix ci for external devs

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/linkerd#399]
our ci job fails for external devs because those ci jobs do not have access to our secret environment variable. ideally ci would still pass when the vars are not available.

current failure, noticed in #398:
```bash
$ ci/coverage-publish.sh
COVERALLS_REPO_TOKEN must be set
ci/coverage-publish.sh returned exit code 1
```

**Comment by gtcampbell** [comment]
Do we just want to disable coverage in this case? Or is there some other way to configure CI to make this work?

**Comment by siggy** [comment]
Unclear, I'm also not sure if that's the only missing env var that will fail ci.

**Comment by olix0r** [comment]
i'd suggest that we just do `./ci/coverage-publish.sh || true` :)
