### ISSUE TITLE
Display success rate rather than latency in main linkerd dashboard

### ISSUE THREAD

**Issue by gtcampbell** [BuoyantIO/linkerd#411]
* Replace the per-client latency line graph (which updates once per minute, making it somewhat confusing) with a success rate line graph. The graph should be pinned at the top to 100%, i.e. the top line should always be 100%, but the bottom can autoscale.

* Replace the "successes" counter with a success rate. Make this the top left element of the per-client table, i.e. the top row is "Success rate" and "Connections", and the bottom row is "Requests" and "Failures".

* Have the line colors next to each cell in the per-client table just be the color of the client line.

* Have the success rate text color change flip to red once it drops below 90%. (Hacky, but it's a start.)

**Comment by olix0r** [comment]
retries don't occur at the client level, so it would be difficult to display the serverside successrate in the client graph.

**Comment by wmorgan** [comment]
I see. As a starting point, maybe we show a per-server success rate in the UI--that will capture retries, and we have some space for it visually on the page. That's not a perfect solution, but should be useful in the common case of one server per router.

**Comment by rmars** [comment]
Things I will do:
* Add back the horizontal client colour line
* Have the graph scaling be "downward" ie we want to compare against 100%

**Comment by wmorgan** [comment]
Updated the description with the latest Product Vision. This ticket is scoped to changes to the client section. I'll make another ticket to capture changes to the server section.
