### ISSUE TITLE
Document requirements for "linkerd-friendly" services

### ISSUE THREAD

**Issue by gtcampbell** [BuoyantIO/linkerd#422]
Document the facilities required to support linkerd features like tracing and per-request routing.

For HTTP, that means forwarding `L5d-*` and `Dtab-*` headers.

**Comment by wmorgan** [comment]
FWIW I wouldn't call this "compatible". All services are linkerd compatible if they speak HTTP, thrift, mux, etc. It's only if you want extended capabilities like distributed tracing and per-request routing that you have to do header forwarding.

But I agree it should be documented.

**Comment by endzyme** [comment]
https://linkerd.io/doc/0.7.0/linkerd/protocol-http/#http-headers - I think this can be closed now, if I've understood the ask correctly.

**Comment by wmorgan** [comment]
Yeah, I think so. Closing. (BTW we're changing some of these headers in the next release.)
