### ISSUE TITLE
Requests to k8s API do not include a Host header

### ISSUE THREAD

**Issue by obeattie** [BuoyantIO/linkerd#427]
Requests that linkerd makes to the k8s API do not include a `Host` header, and requests like these are – for better or worse – [rejected by all Go HTTP servers](https://github.com/golang/go/blob/master/src/net/http/server.go#L782-L784) 😞. This is also in contravention of the HTTP 1.1 spec which [says](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23):
>A client MUST include a `Host` header field in all HTTP/1.1 request messages

**Comment by olix0r** [comment]
yeah, this broke in the [last release](https://github.com/BuoyantIO/linkerd/commit/f8fadab9dfac00c5566119a237095b60e731cc6c) -- we probably need a better k8s integration test
