### ISSUE TITLE
statsd telemeter

### ISSUE THREAD

**Issue by taion809** [BuoyantIO/linkerd#429]
Good Evening Linkerd.

We currently have some finagle stats reporters sending to local statsd collectors, it would be really great if we could configure linkerd to do the same.  In the short term it's possible for us to write a script to pull these metrics on an interval but long term it would be really neat if this were configurable.

**Comment by olix0r** [comment]
There's a new Telemeter plugin API (yet to be fully documented) that supports pluggable stats receivers.  The default one exports metrics on /metrics.json; but we'd also accept a PR that adds a statsd-push telemeter.

**Comment by andersschuller** [comment]
@olix0r Do you have any thoughts on how you would like this (and to some extent the other telemeter plugins) to be implemented? Would you be happy to depend on an external library (for example something like the [java-statsd-client](https://github.com/tim-group/java-statsd-client)), or would you prefer to have it implemented from scratch? I suppose either way it should become a separate `telemetry-statsd` project, like the existing `telemetry-tracelog`?

**Comment by Ashald** [comment]
@andersschuller are you going to work on this? We also need this and I thought that someone from our team would give it a try soon. OTOH, if you're working on it we would be happy to help you with testing.

**Comment by andersschuller** [comment]
@Ashald I was considering working on this a bit over the next few days. I just thought I would first confirm what I've been thinking so far. Since I'm quite new to the project, I have pretty much just been getting familiar with how the project is set up and how the metrics work. I haven't done any actual coding yet, so I would be just as happy to pick up one of the other related issues.

**Comment by olix0r** [comment]
@andersschuller good question. It's definitely _preferable_ to do this in finagle so we get the same level of visibility and control over the client.  However, if there's an existing library that works reasonably well, we can stick it in a FuturePool and see how that works out for us

I might suggest that this be developed as a Telemeter plugin outside of the linkerd repo and when it's generally useful and appealing and we're happy with how it works, we can promote it as an official component.  We're of course happy to help through this -- I'm not trying to blow this off, but I want to make sure that the features that land in the linkerd repo are in a place that we're comfortable maintaining them. The plugin architecture allows us to be a little more incremental about this sort of thing.

Does this make sense?

**Comment by masonoise** [comment]
Yes, we're having pain because of the lack of statsd telemetry as well. We need to feed the metrics into InfluxDB using telegraf, and without statsd format it's very difficult to make proper use of the data.

**Comment by wmorgan** [comment]
@Ashald @andersschuller @taion809 Is this issue still important to you guys?

@masonoise you noted on Slack that the telegraf Prometheus input plugin wasn't a great solution. Can you clarify a little bit what the problem with that approach is? (Not a telegraf expert.)

**Comment by Ashald** [comment]
@wmorgan yeah, we actually working on setting up metrics aggregation right now and linked/namerd is on the short list for this or next week.

> you noted on Slack that the telegraf Prometheus input plugin wasn't a great solution
Meh, that was our plan. :( Well, another good reason for contribution, I guess? :) cc @olgert

**Comment by masonoise** [comment]
@wmorgan I'm not a telegraf/Prometheus expert at all either, but what I know is that our metrics pipeline is set up to ingest statsd-format metrics. I took the telegraf plugin for Prometheus data and modified it to convert the Prometheus-style metrics coming out of Linkerd into statsd-format, and also added a prefix ("linkerd.") to help filter. That's got metrics flowing into our system and we hoped it would do the trick but it's not quite good enough. The telegraf statsd plugin supports template specifications which allows metrics to get filtered into the appropriate places before getting sent down the pipe, which is the key to organizing the data coming in. That's not possible using the Prometheus plugin unfortunately. So we really do need the statsd metrics coming out of linkerd. The only other option would be for me to take the telegraf statsd plugin and hack it to read the JSON or Prometheus metrics out of linkerd, which is clearly not the right way to go...

**Comment by wmorgan** [comment]
@masonoise Thanks, that's helpful. Could you write a script to transform the metrics before telegraf ingestion to the desired state? Or maybe modify the telegraf Prometheus plugin to have template specifications similar to the statds plugin? Not sure if either of those are good long-term solutions, but they might be reasonable short-term ones to get you unblocked.

**Comment by masonoise** [comment]
@wmorgan Modifying the Prometheus plugin is what I did, but it's not so easy. We have metrics going in now because of my modification, but it's not sufficient because we can't properly filter the metrics in Grafana this way. The statsd plugin supports templating, which is what we need. As-is we can't filter sufficiently to build useful dashboards.

**Comment by leozc** [comment]
Hello all,
Sorry for being late to the party, any plan/progress on the statd plugin for linkers/namerd ? We are on the same boat :-), and would love to see if there is any work been done.

**Comment by bashofmann** [comment]
As an alternative: We are using diamond (https://github.com/python-diamond/Diamond) to collect system metrics and push them to graphite, so a diamond is installed on every server anyways. I just pushed the small collector for diamond that we wrote to call the linkerd metrics endpoint here https://github.com/researchgate/diamond-linkerd-collector

**Comment by masonoise** [comment]
Thanks for the thought, @bashofmann -- I'm not sure that would do it for us because we're storing metrics in Influxdb for Grafana dashboards so the statsd metrics format (and the telegraf templating) is essential for us to get proper dashboarding and alerting. I'll look into it in case it might do the trick, though.

**Comment by siggy** [comment]
We are initiated work on this at Buoyant. If you have opinions about the format/labeling of a statd telemeter, please share. We will likely use `/admin/metrics.json` as a starting point, and modify as it makes sense for statsd.

**Comment by masonoise** [comment]
This is great news, thanks. We'll be happy to test it out when it's ready to go. We use telegraf so a key for us is the templating in order to feed to Grafana for dashboards. Being able to filter on labels such as service is probably obvious, but it's what we're looking forward to: having dashboards that can show latency/error rates broken down by service and by host will be fantastic.

**Comment by olgert** [comment]
Great news! We are also using telegraf, and it will be amazing, if linkerd could push stats in "[Influx Statsd]( https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd#influx-statsd )" protocol as an option, which is statsd enhanced with tags. However, transformation templates will also work for us.

**Comment by siggy** [comment]
Hey folks, we have a very-not-production-ready branch up for testing. If you have a moment, we'd love some feedback:
https://github.com/BuoyantIO/linkerd/tree/siggy/statsd

With a `hopsoft/graphite-statsd` test setup, we have it writing three metrics types:
- counters: `stats_counts.linkerd_l5d-uuid-*`
- histograms: `stats.timers.linkerd_l5d-uuid-*`
- gauges: `stats.gauges.linkerd_l5d-uuid-*`

Let me know if you need help generating a jar/executable/plugin/docker image.

**Comment by wmorgan** [comment]
@masonoise @olgert @leozc would love to get your input on the prototype above ^.

**Comment by Ashald** [comment]
@wmorgan sure! I'll spin up a build and ask @olgert to play with it, hopefully today or tomorrow

**Comment by leozc** [comment]
@wmorgan sure, I will look at end of this week or early next week.

**Comment by leozc** [comment]
@siggy  Thanks very much for working on this :-)

**Comment by robbfoster** [comment]
Yes, thanks very much for doing this.  It seems to be mostly working well.  I've got one little problem where I am getting errors in telegraf along the lines of (these are just a sample)

{noformat}
2017/01/10 12:01:05 E! Error: splitting '|', Unable to parse metric: linkerd.rt.int-http.dst.path.http.1_1.GET.10_0_2_15:4140.pending:0|g
2017/01/10 12:01:05 E! Error: splitting '|', Unable to parse metric: linkerd.rt.int-http.dst.id.$.inet.10_0_2_15.8888.path.http.1_1.GET.10_0_2_15:4140.pending:0|g
{noformat}

The theory is that the parser doesn't like the :4140 and the :0 in the same metric name, but that is only a guess.

**Comment by olgert** [comment]
@robbfoster The problem is that `:` is reserved by statsd protocol (it separates metric name from its value) and can't be used in metric name. xref: https://github.com/BuoyantIO/linkerd/pull/898#discussion_r95265487

**Comment by siggy** [comment]
@robbfoster @olgert: nice catch, thanks! i've updated the PR with a fix: https://github.com/BuoyantIO/linkerd/pull/898/commits/20ab41fa2069976b75966b5a0bcebec7ef4682a1

**Comment by robbfoster** [comment]
And all my errors have gone away.  Thanks for the quick turnaround.

**Comment by olgert** [comment]
Thanks for taking care of this! IMO, this is pretty good as a first implementation. As a next step we could add tagging support and create 3 different `statsd_backend` implementations for each statsd dialect:
1. etsty (default)
2. influxdb
3. datadog
How does it sound for you guys?

**Comment by siggy** [comment]
@olgert: i think that sounds good. i'm inclined to ship this as-is to get more folks kicking the statsd tires, and then iterate with the various protocol extensions. i'm optimistic the extensions should be relatively straightforward.

**Comment by leozc** [comment]
@olgert @siggy  

Thanks very much to make this happen, it is certainly an important feature in the coming release!

In the next step, I would suggest we add a new flag called

>  provider_type

which add provider specific tags into the metrics. 

Here are the examples I've found, they are pretty much the same code, only differences are the  string formatter in the `send` and the format of the `tags`.


DataDog:
https://github.com/DataDog/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java

InfluxDB
https://github.com/njawalkar/java-influx-statsd-client/blob/master/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java

**Comment by siggy** [comment]
Thanks for all that detail @leozc. Mind filing a ticket summarizing this request?

**Comment by olgert** [comment]
Thanks everyone for the effort!
