### ISSUE TITLE
have linkerd HTTP error messages link to the dtab playground

### ISSUE THREAD

**Issue by wmorgan** [BuoyantIO/linkerd#445]
As per discussion on Slack:

New users often have trouble configuring the dtab, and the error behavior currently is a somewhat obscure plain-text message:

```No hosts are available for /http/1.1/POST/api-close, Dtab.base=[/http/1.1/*=>/#/io.l5d.k8s/linkerd/http], Dtab.local=[]. Remote Info: Not Available```

Ideally, this error message would have a link to a pre-populated dtab playground (including the path and Dtab.base) so that users could quickly debug the dtab trace. This wouldn't capture non-dtab issues, but it would speed up the debugging process when trying to configure things the first time.

**Comment by wmorgan** [comment]
(Later work might included a fancier error page with some diagnostic tips for other types of errors.)

**Comment by adleong** [comment]
closing in favor of #453
