### ISSUE TITLE
Allow absolute path definition in filesystem namer

### ISSUE THREAD

**Issue by apakulov** [BuoyantIO/linkerd#449]
Current configuration only supports relative directories inside linkerd home folder to setup **rootDir**. When you're trying to define absolute path for **names/rootDir** it will use **linkerd/disco** folder as a fallback instead.

Config example:

```
namers:
- kind: io.l5d.fs
  rootDir: /usr/local/var/lib/linkerd
```

**Comment by Ashald** [comment]
IDK since when, but at least `0.7.5` supports absolute paths in `rootDir`. Moreover since fe5943bc53a3e305275b023abc19fc2a86c1ae3b @adleong added a test that uses absolute path for `rootDir`.

**Comment by olix0r** [comment]
Thanks for pointing this out, @Ashald!

**Comment by Ashald** [comment]
NP. ;)

**Comment by apakulov** [comment]
@Ashald @olix0r thanks!
