### ISSUE TITLE
Admin dashboard graphs lag over time

### ISSUE THREAD

**Issue by klingerf** [BuoyantIO/linkerd#456]
Am seeing an issue where the scrolling dashboard graphs begin to lag behind actual clock time when left open for a few hours.  The net effect of this is that the most recently displayed graph value does not match the summary value that's displayed elsewhere in the value.

**Comment by klingerf** [comment]
![screen shot 2016-06-02 at 1 59 22 pm](https://cloud.githubusercontent.com/assets/9226/15759030/58f457ee-28ca-11e6-8965-d0497e20862f.png)

**Comment by wmorgan** [comment]
Upon further investigation, issue was that the top-most graph *grows* horizontally when switching tabs. (Under certain window sizes, in Chrome). So switching back and forth between tabs can cause "lag" because the newest portion of the graph is hidden from view.
