### ISSUE TITLE
Lost documentation entry for Dtab-local header in 0.6.0

### ISSUE THREAD

**Issue by masonoise** [BuoyantIO/linkerd#465]
The documentation for 0.5.0 includes a section at the end of https://linkerd.io/doc/0.5.0/config/ describing the Dtab-local header, and that seems to have gotten lost in the 0.6.0 documentation set. It's a really important and useful feature so hopefully this is a documentation updating oversight and not reflective of a change being made to remove the functionality!

The lost section:

**PER-REQUEST ROUTING OVERRIDES**
For HTTP calls, the `Dtab-local` header is interpreted by linkerd as an additional rule to be appended to the base dtab. Since dtab rules are applied from bottom to top, this allows overriding of the routing rules specified `baseDtab` for this request.

Note that linkerd copies this header to the outgoing (proxied) RPC call. In this manner, override logic can be propagated through the entire call graph for the request.

**Comment by wmorgan** [comment]
Thanks, Mason! I think this was an oversite in 28f74e6bd9 -- definitely not a loss of functionality!

**Comment by masonoise** [comment]
Great, I didn't think so -- I'm testing it out with 0.6.0 and having some trouble but I can tell the header is being processed. Some examples in the documentation of using it would definitely not be a bad thing as well. Thx.

**Comment by adleong** [comment]
Documented here: https://linkerd.io/config/0.8.1/linkerd/index.html#context-headers
