### ISSUE TITLE
Add finagle-zipkin-core to twitter-develop.sh

### ISSUE THREAD

**Issue by cacoco** [BuoyantIO/linkerd#476]
You're probably going to want to add finagle-zipkin-core here: https://github.com/BuoyantIO/linkerd/blob/master/ci/twitter-develop.sh#L101

after this change: https://github.com/twitter/finagle/commit/989edc58084fa01b6e6557ff5b6adda594ba469f

see: https://github.com/twitter/twitter-server/commit/b5d03dec575e0cc42cf128cfcc0cd8c00da1312f

**Comment by wmorgan** [comment]
Thanks, Chris! (And hi!!!!)

**Comment by cacoco** [comment]
@wmorgan (hey Will!) No problem.

**Comment by olix0r** [comment]
thanks @cacoco! really appreciate the heads-up :D
