### ISSUE TITLE
Standardize Logging Output

### ISSUE THREAD

**Issue by njohns-grovo** [BuoyantIO/linkerd#481]
Hello,
One thing that came up was parsing logs with logstash, the current output from linkerd is as follows

```
Jun 15, 2016 9:15:26 AM com.twitter.finagle.http.HttpMuxer$$anonfun$4 apply
INFO: HttpMuxer[/admin/metrics.json] = com.twitter.finagle.stats.MetricsExporter(<function1>)
Jun 15, 2016 9:15:26 AM com.twitter.finagle.http.HttpMuxer$$anonfun$4 apply
INFO: HttpMuxer[/admin/per_host_metrics.json] = com.twitter.finagle.stats.HostMetricsExporter(<function1>)
I 0615 13:15:26.713 THREAD67: linkerd 0.6.0-SNAPSHOT (rev=3a2ac9a84f723066d8f0ceb682800eeb13b5ee2d) built at 20160615-091509
I 0615 13:15:26.844 THREAD67: Finagle version 6.35.0 (rev=4f353f2d009ea37dc853bbee875a04cf8f720b52) built at 20160427-114558
I 0615 13:15:27.505 THREAD67: Loading tracer: com.twitter.finagle.tracing.NullTracer$@735e537c
I 0615 13:15:27.583 THREAD67: /admin => com.twitter.finagle.Filter$$anon$1
```

Which is 3 different logging formats, how could this be standardized into a single logging format?

Edit: and in addition to the above would it be possible to specify the logging format in order to do things like condense stack traces into a single line?

**Comment by wmorgan** [comment]
Hi Nicholas,

Thanks for the issue! It would be possible to standardize these formats, and we're certianly not opposed to it, but it would be a fair amount of work--various underlying frameworks do various things for logging and unifying them all would be non-trivial. (And historically, we've moved away from log parsing in favor of metrics to understand aggregate behavior, so we haven't had much motivation to do this in the first place.)

Do you have a specific use case you want to address? E.g. if you're looking to track exceptions, these are exposed in `failures/*` counters in `metrics.json`.

**Comment by njohns-grovo** [comment]
Hello,
Sorry I took a dive into the code and I see changing the log format for everything is a bit of work, specifically i'm looking into having a linkerd instance per host and have logs shipped to logstash (which is how our current infrastructure is setup).  One issue that we have had come up with finagle based services is that an exception can generate a lot of broken log entries in logstash.

I think it might be easier to answer "how can i integrate linkerd's logs with logstash/syslog/{insert-log-aggregation-here}" instead of rummaging through finagle, twitter-server, etc 😬

**Comment by wmorgan** [comment]
Yep, I think that makes sense. I have never used logstash--but I did find some search results about parsing JVM exceptions, e.g. https://sematext.com/blog/2015/05/26/handling-stack-traces-with-logstash/. Would that help with your use case?

We can also investigate smashing these things into one line within linkerd. I'm not sure what that would entail.

**Comment by njohns-grovo** [comment]
Thanks for that, i'll be doing some experimentation

This is what i've done with logback for finagle stuff so far
```xml
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>ts="%date" level="%level" traceId="%-25X{traceId}" ctx="%-25logger{0}" msg="%msg"%replace(%xException){"\n", "\\n"}%nopex%n</pattern>
        </encoder>
</appender>
```

I think this will end up in a cookbook somewhere, fitting finagle into our infrastructure has been more difficult than expected but I dont think its something linkerd needs to solve 😀   I'm going to close this one if I find a solution i'll just ping slack :)

**Comment by wmorgan** [comment]
Alright, feel free to ping or reopen if necessary. Also, if you get a viable solution going with logstash, please post on Slack or dump it here... I'd love to add it to the docs somewhere. I'm sure you're not the only person who'll be doing this.

**Comment by gudyo** [comment]
Does anyone know if any improvements have been made on this? Is it possible to get all logs to be in a single format, like JSON?

**Comment by dadjeibaah** [comment]
@gudyo we haven't done any work on this issue, mostly because of the reasoned specified in the previous comments. What is your particular use case for having log output in JSON format?
