### ISSUE TITLE
Can binaries be made available in Maven repo/downloadable for windows user ?

### ISSUE THREAD

**Issue by GolfRider** [BuoyantIO/linkerd#491]
Hi , 
I was trying to experiment with Linkerd.  
It would be great, if we can have the binaries available on maven repo.
For windows users, there is no easy way.
I tried building the binaries , but it was failing.
It would be great if the binaries are made available as downloadable on the github repo
so we can start readily on windows.

Appreciate some help here.
Thanks

**Comment by olix0r** [comment]
We've recently started publishing linkerd artifacts. http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.buoyant%22 !
