### ISSUE TITLE
Improve ergonomics of experimental feature acknowledgement

### ISSUE THREAD

**Issue by wmorgan** [BuoyantIO/linkerd#53]
In order to use the Consul namer, you have to refer to it as `io.l5d.experimental.consul` in the namer config block, but `io.l5d.consul` in the dtab. (This may also be the case for other experimental namers.)

This is somewhat confusing, especially since non-experimental namers are matched in these two sections. At a minimum, this discrepancy should be documented.

**Comment by adleong** [comment]
Fixed in https://github.com/BuoyantIO/linkerd/releases/tag/0.6.0
