### ISSUE TITLE
Support service registration at service discovery 

### ISSUE THREAD

**Issue by mielientiev** [BuoyantIO/linkerd#548]
It would be great if linkerd have API for registering service at service discovery (Zookeeper, Consul, Eureka, etc). It gives an opportunity easily change Service Discovery without changing a code.

**Comment by wmorgan** [comment]
Thanks for the feedback, @mielientiev! Announcing is on the tentative roadmap and we're putting some thought into how to do this best. (E.g. see https://github.com/BuoyantIO/linkerd/issues/38).

Could you give us a couple details about your use case and environment? How would you like this to work? How would it interact with your deploy tooling? How would you want to configure it? Etc.

**Comment by moderation** [comment]
Are these announcer branches from @adleong part of this work? https://github.com/BuoyantIO/linkerd/search?q=announcer&type=Issues

**Comment by adleong** [comment]
Those branches are exploratory.  We still haven't settled on exactly how this should work.

**Comment by olix0r** [comment]
We've introduced plugin interface to support announcement in https://github.com/BuoyantIO/linkerd/pull/368.  If there are specific service registry schemes you'd like to support, please open an issue for each with references to relevant docs.  Thanks!
