### ISSUE TITLE
Add support for multiple namespaces in namerd

### ISSUE THREAD

**Issue by jacob-koren** [BuoyantIO/linkerd#550]
Use case 1:
========
Two automated process that effect the namerd dtab happens concurrently. The reliance on single dtab creates a race condition. The dtab one process gets, modify & update might be changed by another in the middle of the process.
Think of a blue/green automated upgrade that happens on two different apps at the same time.

Use case 2:
=========
Creating a small dtab just for testing purposes, or a temporary application, without changing the default dtab all other services use ...

**Comment by wmorgan** [comment]
I believe that the race condition issue is avoided currently thanks to the `Etag` header enforced by the namerd API (which, I'll admit, is totally undocumented).

Use case 2 is an area of active discussion for us. Some of this use case can be captured by the override header (https://linkerd.io/doc/0.7.1/linkerd/protocol-http/#user-headers), but there's definitely more to be done.

**Comment by adleong** [comment]
To expand on William's first point, when you request a dtab from the namerd API, an Etag header is returned that represents the dtab's version.  When updating a dtab, you can set an "If-Match" header with that value and the update will only be applied if the version matches.

We'll work on getting this documented.

**Comment by olix0r** [comment]
Please reopen if you have any more questions!
