### ISSUE TITLE
HA support for linkerd crash or reboot

### ISSUE THREAD

**Issue by calvin1978** [BuoyantIO/linkerd#571]
what happen to the client when local linkerd reboot for upgrade?

**Comment by wmorgan** [comment]
Hi Calvin,

linkerd is modeled as an out-of-process client-side network stack, so HA concerns are intended to be deferred to another layer. If a linkerd instance is down, it should be handled as the client being down. Then you can treat linkerd upgrades or failures just as you do with client upgrades or failures--rolling deploys, rescheduling via something like Mesos or Kubernetes, etc.

The other option is that you can have clients talk to multiple linkerd instances, and load balance over them. Then you can do a rolling upgrade. This is not ideal in some ways (linkerd is designed to save you from implementing your own load-balancing logic), but it is useful in some cases.

Please let me know if this answers your question.
