### ISSUE TITLE
Dashboard becomes slow with many clients

### ISSUE THREAD

**Issue by obeattie** [BuoyantIO/linkerd#572]
In my setup, I have 130+ backend services, and each of these is represented by a separate client in linkerd. At this number of clients, the dashboard slows to the point of being unusable. I'm not a front-end engineer and I haven't investigated this hypothesis, but I suspect this is due to the number of charts being updated in real-time.

**Comment by rmars** [comment]
Seems quite likely! Let me try making the clients collapsible as you mentioned in slack, so that for large numbers of clients this page isn't doing so much.
