### ISSUE TITLE
pluggable authentication

### ISSUE THREAD

**Issue by asheshambasta** [BuoyantIO/linkerd#582]
In our use case, we're planning to use Linkerd for more than just service discovery and linking. We're looking at;
- dividing resources into static and auth. resources. Static resources can be accessed without authentication and auth. resources require authentication.
- for static resources, linkerd can forward requests to the target service without much
- for auth. resources, linkerd should be able to query an authentication service (also part of the fleet of services registered on Consul/etc.)
  - this service signs requests with the user's data
  - this signature is passed downstream to other services that can just extract user data from the request headers and are concerned with business logic.

I'm looking at writing a simple plugin that can do this, but I wanted to see if you guys agree/disagree with the idea here.
Also, if you guys would suggest a good starting point, that'll be helpful.

**Comment by olix0r** [comment]
Thanks for writing this up, @asheshambasta 

The Identifier plugin interface is probably a great place to get started.

Identifiers essentially expose `Request => Future[(Dst, Request)]` -- meaning that, given a request, they asynchronously find the destination (service) and a potentially modified request.  This would likely be a natural place to extract credentials from the request, call another service, modify the request with a resulting cookie, and choose a destination based on the results of authentication.

Here's an example identifier plugin written in Java: https://github.com/BuoyantIO/linkerd-examples/tree/master/plugins/header-classifier

I expect that identifiers and plugins are somewhat under-documented; so don't hesitate to ask questions if you get stuck.

**Comment by asheshambasta** [comment]
Thanks for the pointers @olix0r. What would be the best way to access a `Namer` inside the plugin -- basically, I'll need to read some configuration that defines the hostname of the Auth service and then creates a service after resolving the service address, which then would instantiate an instance of the plugin.
Also, I wanted to do a [quick check](https://gist.github.com/asheshambasta/09fb41a442210b913bf94358df63042f) with you guys to see if I'm headed the right way.

**Comment by adleong** [comment]
How are you planning to discover the location of the auth service?  If it's in a known location that can be specified in the config block for your plugin, you can have your config block accept a host/port pair and then create a client which connects to that.  If you need to talk to service discovery to find the auth service, things get trickier.

**Comment by asheshambasta** [comment]
@adleong yeah, that was what I was worried about – I wanted something that could just accept the hostname and resolve it through SD the same way it would do for other services. That makes more sense for us because the service handling authentication in our case is one of the services registered on consul and can move around.

**Comment by adleong** [comment]
Currently you can create a finagle client in your plugin using a classpath namer (e.g. `/$/inet/1.2.3.4/8080`) but I don't think you have access to the namers configured in the linkerd config.  I've filed https://github.com/BuoyantIO/linkerd/issues/596

**Comment by asheshambasta** [comment]
@adleong ok, seems like a no go then – I'm keeping my eyes on #596. In our scenario, its impossible to know the location of the authentication service without resolving it first.

**Comment by olix0r** [comment]
Note! We added support for using namers from identifiers in #616.

I'm going to close this issue for now, but please reopen if you have any more questions.

**Comment by ajagnanan** [comment]
@asheshambasta were you guys able to finish the plugin by chance?
