### ISSUE TITLE
Make configured namers available to plugins

### ISSUE THREAD

**Issue by adleong** [BuoyantIO/linkerd#596]
linkerd plugins that talk to external services (identifiers, for example) need some way to discover those services.  Make the configured namers available to the plugin so that they can address external services using those namers (e.g. `/#/io.l5d.consul`)

**Comment by olix0r** [comment]
We need to be careful about introducing dependencies between plugin systems. For example, namers should get stats receivers and tracers, so telemeters can't rely on namers.  We'll just need to be careful/explicit about how these features are composed.

**Comment by asheshambasta** [comment]
This will definitely be great for our use case.

**Comment by adleong** [comment]
Good point, @olix0r.  I think that since namers are "top-level" in the config, making them available to router-level plugins keeps the dependencies one-directional and sane.

**Comment by Ashald** [comment]
We would glad to have this feature as well! :)

**Comment by zircote** [comment]
👍 Looking forward to this one as well, thank you @adleong
