### ISSUE TITLE
Retried HTTP requests drop chunked bodies

### ISSUE THREAD

**Issue by obeattie** [BuoyantIO/linkerd#599]
When HTTP requests are retried, it appears that they lose their body when using `Transfer-Encoding: chunked`. 🕳

The _initial_ request (before retries) is passed to the upstream server correctly by linkerd.

```
PUT / HTTP/1.1
Host: thing
Transfer-Encoding: chunked
Accept: */*
Content-Type: application/x-www-form-urlencoded
L5d-Ctx-Trace: U1nuHsM0tDjlY4pt28pW0eVjim3bylbRAAAAAAAAAAI=
L5d-Dst-Concrete: /#/io.l5d.fs/thing
L5d-Dst-Logical: /http/1.1/PUT/thing
L5d-Reqid: e5638a6ddbca56d1
User-Agent: curl/7.43.0

1a
Lorem ipsum dolor sit amet
0
```

But the retry loses the body:

```
PUT / HTTP/1.1
Host: thing
Transfer-Encoding: chunked
Accept: */*
Content-Type: application/x-www-form-urlencoded
L5d-Ctx-Trace: /D3iLPS/al7lY4pt28pW0eVjim3bylbRAAAAAAAAAAI=
L5d-Dst-Concrete: /#/io.l5d.fs/thing
L5d-Dst-Logical: /http/1.1/PUT/thing
L5d-Reqid: e5638a6ddbca56d1
User-Agent: curl/7.43.0

0
```

I've put together [a simple server](https://gist.github.com/obeattie/00ee3ba4ada7fe693ef8672ec76a10e4) as a test case to show this behaviour. It rejects valid requests as 500, triggering the retry when linkerd is configured with the `io.l5d.retryableIdempotent5XX` response classifier.

This does _not_ happen however when `chunked` encoding isn't used. In that case, the retry has the correct body.

**Comment by olix0r** [comment]
Thanks for reporting this. This was definitely an oversight -- I think we'll need to change the retry policies to not consider any request as retryable that has a chunked body.  With chunked bodies, we explicitly do not want to buffer the entire body; but retrying these requests would require that we are able to re-stream the body, which isn't possible without buffering.

I'll submit a change to the retry classifiers to correct this.

**Comment by obeattie** [comment]
I can understand the desire not to buffer large bodies, but I think this (and any other conditions which would make a request non-retryable) should be documented very clearly.

**Comment by olix0r** [comment]
@obeattie agreed completely. As I said, this was an unintended consequence, and we simply hadn't tested retries with chunked request bodies.  I'm updating classifiers to consider such requests non-retryable. I'll update the documentation as well.
