### ISSUE TITLE
Delegate API / Namerd UI doesn't handle /$/fail (!) properly

### ISSUE THREAD

**Issue by Ashald** [BuoyantIO/linkerd#604]
Having a namespace `default`:
```
/env#/foo-123=>/$/inet/127.0.0.1/80;
/env#/foo-456=>~;
/service/foo=>/env#/foo-123 | !;
/service/foo=>/env#/foo-456 | !;
```
expected behavior to see `neg` for `/service/foo`.

The `resolve` endpoint handles that just right:
```
$ curl -s "$NAMERD_URL/api/1/resolve/default?path=/service/foo"
{"type":"neg"}
```
but not the Namerd UI (which is presumably powered by `delegate` API endpoint):
![screen shot 2016-08-24 at 18 36 05](https://cloud.githubusercontent.com/assets/397987/17950519/bca9aeb0-6a29-11e6-8cc0-19b06bfe2f8b.png)

**Comment by olix0r** [comment]
Do you get the same behavior if you replace `!` with `/$/fail`?

**Comment by Ashald** [comment]
Yes, exactly the same behavior.

**Comment by adleong** [comment]
I've got some tweaks to the way the delegation trees are displayed that makes it more clear what's going on.  What do you think about this:

<img width="1266" alt="screen shot 2016-08-26 at 11 20 28 am" src="https://cloud.githubusercontent.com/assets/3979810/18016097/5de5e9aa-6b7f-11e6-96dd-8ec20146927f.png">

This is a separate issue, but I think that response from `resolve` is actually incorrect.  In the case of Neg, it should fall back to the next arm of the Alt so it should return Fail.

**Comment by Ashald** [comment]
Yeah I like the new representation better - it it expands alternatives in `Dentry` `dst`'s and it's easier to analyze the output. 👍

**Comment by Ashald** [comment]
So, was it the issue of rendering? Or there is also a bug in delegate API?

**Comment by adleong** [comment]
Not a bug as much as just a confusing way of displaying the information.  Hopefully what we have now is more clear.

**Comment by Ashald** [comment]
Ah, I see. Cool - thanks!
