### ISSUE TITLE
Linkerd & Namerd admins doesn't work in Kubernetes

### ISSUE THREAD

**Issue by moleksyuk** [BuoyantIO/linkerd#610]
Hi guys,

We have deployed Namerd and Linkerd to Kubernetes and exposed admin console through such url:

Namerd - https://api.internal.k8s.company.com/api/v1/proxy/namespaces/stage/services/namerd-admin:9991/
Linkerd - https://api.internal.k8s.company.com/api/v1/proxy/namespaces/stage/services/linkerd-admin:9990/

But they don't work due to:

```
jquery.min.js:4 GET https://api.internal.k8s.company.com/files/template/dentry.template 404 ()send @ jquery.min.js:4ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4(anonymous function) @ dashboard_delegate.js:6
jquery.min.js:4 GET https://api.internal.k8s.company.com/files/template/delegatenode.template 404 ()send @ jquery.min.js:4ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4(anonymous function) @ dashboard_delegate.js:7
jquery.min.js:4 GET https://api.internal.k8s.company.com/files/template/error_modal.template 404 ()send @ jquery.min.js:4ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4(anonymous function) @ dashboard_delegate.js:8
jquery.min.js:4 GET https://api.internal.k8s.company.com/files/template/delegator.template 404 ()send @ jquery.min.js:4ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4(anonymous function) @ dashboard_delegate.js:9
```

As I see in `AdminHandeler.scala` it contains hardcoded relative paths to root.

Is it possible to configure admins to be working in correct way in Kubernetes?

**Comment by wmorgan** [comment]
Hi @moleksyuk. Sounds like a bug (but not Kubernetes specific). We'll take a look. Thanks!

**Comment by olix0r** [comment]
We've been tracking this in #397. We should extend the admin configuration to support a configurable resource root.
