### ISSUE TITLE
k8s namer does not handle ungraceful watch termination

### ISSUE THREAD

**Issue by obeattie** [BuoyantIO/linkerd#617]
The Kubernetes namer establishes a watch on endpoints within a namespace so it has up-to-date topology information. Watch events are delivered in a streaming HTTP response, and if the connection between linkerd and the k8s API is severed (ie. not terminated gracefully), linkerd may have stale discovery information and never recovers without a restart. 🚑 

This [test case](https://gist.github.com/obeattie/420de5bf801b3cae0c2da96258d56546) exhibits the problem. The Go program in there acts as both a mock k8s API and a downstream `emojum` service.

1. Fire up linkerd using the config from the Gist and the k8s API mock (`go run k8s-fake.go`)
2. Make a (successful) request via linkerd to the `emojum` service:
   ```bash
$ curl -v "http://localhost:8080/" -H "Host: emojum"
> GET / HTTP/1.1
> Host: emojum
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 01 Sep 2016 08:04:26 GMT
< Content-Length: 4
< Content-Type: text/plain; charset=utf-8
🐹
```

   Observe from the mock's logs that linkerd has made the expected call to list endpoints and establish a watch:
   ```
2016/09/01 09:07:06 [127.0.0.1:8001] /api/v1/namespaces/srv/endpoints
2016/09/01 09:07:08 [127.0.0.1:8001] /api/v1/namespaces/srv/endpoints?watch=true&resourceVersion=1
2016/09/01 09:07:08 [emojum] /
```
3. Instruct the mock to tear down the watch connection:
   ```bash
$ curl -v "http://localhost:8001/control?action=terminate"
> GET /control?action=terminate HTTP/1.1
> Host: localhost:8001
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 01 Sep 2016 08:08:34 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
```

   Observe in the mock's logs that the watch was terminated, and linkerd **successfully** re-established the watch:
   ```
2016/09/01 09:10:02 [localhost:8001] /control?action=terminate
2016/09/01 09:10:02 Watch ended: terminated
2016/09/01 09:10:02 [127.0.0.1:8001] /api/v1/namespaces/srv/endpoints
2016/09/01 09:10:02 [127.0.0.1:8001] /api/v1/namespaces/srv/endpoints?watch=true&resourceVersion=1
```

   *Note: This step isn't really necessary, it's just to illustrate that linkerd is correctly handling more graceful termination*
4. Now, forcefully stop (Ctrl+C/`SIGINT`) the mock process and restart it. Notice that this time, linkerd **does not** re-establish the watch: 😱 

   ```bash
signal: interrupt
$ go run k8s-fake.go
2016/09/01 09:12:18 Listening on :8001…
```

-----

From what I've seen, a `ChannelClosedException` is returned by the request reader, but the [code to re-establish the watch](https://github.com/BuoyantIO/linkerd/blob/e948ad13807799649af691008935fa513eb83939/k8s/src/main/scala/io/buoyant/k8s/Watchable.scala#L95-L109) is never run. I mentioned what I thought was the cause of this issue [on Slack yesterday](https://linkerd.slack.com/archives/finagle/p1472644388000044), but I think I was quite off-base and I don't really understand how the exceptions propagate internally. I'll be fascinated to see how to solve this; I've really enjoyed poking at the internals although I think I need some help from the experts. 👷

**Comment by wmorgan** [comment]
Thank you for a very detailed repro!

**Comment by adleong** [comment]
Thanks for the repro, @obeattie!  I think I now see what you meant the other day about `AsyncStream` and exceptions.  An exception in an `AsyncStream` will effectively halt traversal over the stream.  I think we need to make sure that exceptions don't make it into the stream, even if we encounter them while reading from the `Reader`.  I'll put together a unit test and fix, and make sure to validate it against the repro steps you posted.
