### ISSUE TITLE
support linkerd-to-linkerd per-host deployments in k8s

### ISSUE THREAD

**Issue by adleong** [BuoyantIO/linkerd#660]
Deploying 1 linkerd per-node instead of 1 per-pod can be far more resource efficient when tens or hundreds of pods run on each node.  Unfortunately, this presents several challenges that must be overcome to have a functioning linkerd-to-linkerd setup:

1. Services must be able to locate the local linkerd so that they can send outgoing traffic to it.  A service can request the set of linkerd endpoints from the a linkerd daemonset service api.  Since each node is a distinct /24 subnet, the service can then pick the linkerd endpoint on it's /24 subnet and send outgoing traffic to that address.

2. linkerd must be able to determine which hosts to which to send traffic.  i.e. which hosts have instances of the target service running on them.  https://github.com/BuoyantIO/linkerd/issues/658

3. When receiving incoming traffic, linkerd must be able to locate the local service to which to route the traffic. https://github.com/BuoyantIO/linkerd/issues/659

**Comment by OleksandrBerezianskyi** [comment]
Hey Alex, that is exactly what we together with @moleksyuk are planning to do. So 1 and 2 is solved by having linkerd running as a deamonset on the **host** network. In this case linkerd still can connect to namerd to  resolve endpoints (2.) and every pod should connect on the well known port of the hosting node.

There are a few ways to pass the hosting node domain name to the pod:

1. Use downward API and parse out host name or IP: http://stackoverflow.com/questions/30690186/how-do-i-access-the-kubernetes-api-from-within-a-pod-container/30739416#30739416
The ugly part of this is that you need to add a script that will do that on the pod startup and push the result into some environment variable, like **K8S-NODE-NAME**
1. Wait for k8s 1.4 and use https://github.com/kubernetes/kubernetes/pull/27880 to do the same but without the script - directly from pod spec

As for 3. we were thinking about getting the information about /24 CIDR from downward API as well and using that on linkerd plugin to filter enpoints to the node-local

Please let us know if you find a better alternative.

**Comment by wmorgan** [comment]
@OleksandrBerezianskyi thanks for the details! Really helpful.

**Comment by wmorgan** [comment]
Found another way to get the host IP via the Kubernetes slack: use the default route for the pod (e.g. by reading /proc).

https://github.com/DataDog/dd-agent/blob/e1086b0c52d3438ea841762623ecb5a0db28645f/utils/dockerutil.py#L157
