### ISSUE TITLE
linkerd not updating namerd rules after laptop suspend/unsuspend

### ISSUE THREAD

**Issue by wmorgan** [BuoyantIO/linkerd#668]
Running linkerd on a laptop is not the intended use case, but I'm filing this in case it's an indication of an underlying issue.

With a linkerd that's been running for ~12 hours and has gone through several laptop suspends and unsuspends, I see policy changes in namerd correctly reflected in the dtab playground, but not in the actual traffic that's been shifted.

Specifically: yesterday I set a rule that sent 90% of traffic to a service called "authors-v2" and 10% of traffic to "authors" (`/host/authors => 9 * /srv/authors-v2 & /srv/authors`). This worked as expected. Now, when I change that rule in namerd (via the Helium UI), I don't see the change in traffic reflected.

E.g. here I've set it to 50-50. Note that the dtab playground correctly reflects this, but the yellow line (authors-v2) continues to receive about 90% of traffic.

![screen shot 2016-09-14 at 11 46 45 am](https://cloud.githubusercontent.com/assets/4026/18525339/e847741a-7a70-11e6-8993-049053b3b530.png)
![screen shot 2016-09-14 at 11 45 52 am](https://cloud.githubusercontent.com/assets/4026/18525338/e83f3e94-7a70-11e6-8480-e01e32d5593c.png)

Metrics snapshot attached.
[metrics.json.gz](https://github.com/BuoyantIO/linkerd/files/473230/metrics.json.gz)

**Comment by adleong** [comment]
Unable to repro.  Closing until this shows up again.
