### ISSUE TITLE
Allow com.twitter.finagle.Http$param$MaxRequestSize to be larger than 2GB

### ISSUE THREAD

**Issue by adambom** [BuoyantIO/linkerd#672]
Currently, http routers are limited to handling request sizes of no larger than 2GB. I have a use case where I want to do streaming file uploads, and requests could be much larger than 2GB. This limit seems fairly arbitrary. I'd like to allow for removing the limit altogether, or at least allowing it to go higher than 2GB.

**Comment by adleong** [comment]
Hi @adambom, I believe that 2GB is the limit is for non-chunked requests.  If you are doing chunked streaming uploads, I don't think you will be subject to the `MaxRequestSize`.

**Comment by adambom** [comment]
The upload is not currently being chunked, which would explain why I'm hitting the limit. Is there any reason to always limit the non-chunked uploads?

**Comment by olix0r** [comment]
Well, the process has to buffer chunked messages.  A 2G unchunked payload could easily cause the process to OOM if you haven't given it at least 3 or 4 G of heap space.  Or a 200M payload would cause the process to OOM if there are multiple concurrent requests... etc.

The limits are there to protect the process against unconstrained memory pressure; and if you want to raise these limits, you need to tune the processes's memory allowance explicitly (there are environment variables that can be used to change the process's default memory settings.

**Comment by wmorgan** [comment]
@adambom if you really want to go down this path we can point you in the right direction (like Oliver says, increase `MaxRequestSize` and change some of the JVM settings to get more memory). But it's almost definitely better to get chunking in there, unless you have some very specific reasons why that's not feasible.

**Comment by Ashald** [comment]
IIRC the problem is a bit deeper - there is fundamental limitation within `netty`. `org.jboss.netty.handler.codec.http.HttpChunkAggregator` has `int maxContentLength` as a constructor parameter. Given that it's signed it means that `HttpChunkAggregator` cannot handle requests larger than 2GB at all. So unless you ready to hack your own version of codec there is no easy way to achieve that.

**Comment by adambom** [comment]
Ok thanks for the explanation. I will look into chunking the request body.
