### ISSUE TITLE
Linkerd should strip all headers listed in the `Connection` header

### ISSUE THREAD

**Issue by fantayeneh** [BuoyantIO/linkerd#676]
`StripConnectionHeader` is removing only the `Connection` Header. 
According to https://www.mnot.net/blog/2011/07/11/what_proxies_must_do not only `Connection` 
but all the headers listed in the `Connection` header should be removed.

Actually to be complete all the Hop-By-Hop headers should be removed both from the Requests 
and the Responses.

**Comment by olix0r** [comment]
Thanks for pointing out this post, @fantayeneh.  Very clear & helpful.
