### ISSUE TITLE
Linkerd should strip all Hop by Hop Headers 

### ISSUE THREAD

**Issue by fantayeneh** [BuoyantIO/linkerd#678]
Linkerd should strip out all  Hop-by-Hop headers from Requests and also from Responses.
https://www.mnot.net/blog/2011/07/11/what_proxies_must_do

The following HTTP/1.1 headers are hop-by-hop headers:
- Connection
- Keep-Alive
- Proxy-Authenticate
- Proxy-Authorization
- TE
- Trailers
- Transfer-Encoding
- Upgrade

**Comment by olix0r** [comment]
We already strip Proxy-Authenticate, Proxy-Authorization and Proxy-Connection headers in ProxyRewriteFilter.  But i fully endorse stripping the rest.

Perhaps it's best to rename StripConnectionHeader to StripHopByHopHeader, and put all of the header-removal logic (including Proxy-* headers), into a single filter.

**Comment by fantayeneh** [comment]
Yes, that was exactly what i would have done. :)
