### ISSUE TITLE
GC latency should not collected  together with request context

### ISSUE THREAD

**Issue by mapix** [BuoyantIO/linkerd#688]
We found GC pause has beed collected into Zipkin in request context.  It will make request latency hard to understand,  may it will be ignored when send to Zipkin?

Here  `/dae_thrift_client_proxy` is our linkerd service:
![screen shot 2016-09-21 at 12 11 46 pm](https://cloud.githubusercontent.com/assets/932699/18697534/a50810e0-7ff4-11e6-8715-475f37ad9041.png)

**Comment by klingerf** [comment]
Hi @mapix, very interesting.  This annotation is added by Finagle's JVM filter, here:

https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/filter/JvmFilter.scala

That filter is present on the default Finagle server stack.  I think that means that any Finagle service, by default, will emit these GC annotations.  linkerd could be updated to specifically exclude that filter, but it seems like having GC annotations might be helpful when looking at traces.  Maybe Zipkin's UI needs to be updated to handle these types of annotations properly?

Which version of the Zipkin UI are you using, by the way?  When I send linkerd annotations to zipkin-1.11.1, I see these annotations represented a bit differently, as follows:

<img width="708" alt="screen shot 2016-09-21 at 1 21 35 pm" src="https://cloud.githubusercontent.com/assets/9226/18727689/b2c3cb5c-7ffe-11e6-819c-445a0e5289d9.png">

As far as I can tell the gantt chart only includes the starting value for the annotation, and does not display the ending value in line with the chart.

**Comment by klingerf** [comment]
For completeness' sake, here are all of the annotations associated with the span in the previous screenshot:

![screen shot 2016-09-21 at 1 27 30 pm](https://cloud.githubusercontent.com/assets/9226/18727818/64cf54ba-7fff-11e6-837a-6daa01af69aa.png)

**Comment by mapix** [comment]
@klingerf 

Yeah, we use a self-implemented Zipkin toolsets . If this GC annotation is collected by intent , i will update our Zipkin UI to fix it.

**Comment by mapix** [comment]
closed for only affect our infrastructure

**Comment by klingerf** [comment]
@mapix Ok, great -- thanks for the additional info!
