### ISSUE TITLE
Create a rewriting namer to allow appending path segments

### ISSUE THREAD

**Issue by adleong** [BuoyantIO/linkerd#695]
It is impossible to append segments to the end of a path using dentries.  Create a rewriting namer that does this.  

This would allow paths like `/host/foo` to be rewritten to `/$/inet/foo/80`.

**Comment by olix0r** [comment]
Alternatively, it may make sense to have an inet namer like `/$/port/80/foo`. I don't have a strong sense of what's preferred.  Appending gets really weird with residuals...
