### ISSUE TITLE
Marathon: Do not add / remove nodes when marathon-marked "unhealthy" nodes in namer

### ISSUE THREAD

**Issue by JonathanBennett** [BuoyantIO/linkerd#704]
As discussed on slack.

When scaling, linkerd routes to "unhealthy" nodes resulting in 502 responses. Assuming there are multiple ways to do this (such as retries) but might be good to add a configuration item to the namer to not route to "unhealthy" instances (and indeed remove them from routing).

/cc @olix0r

**Comment by siggy** [comment]
### linkerd change

The marathon namer can optionally check `app/tasks/healthCheckResults/alive` to determine instance health. Probably near https://github.com/BuoyantIO/linkerd/blob/master/marathon/src/main/scala/io/buoyant/marathon/v2/Api.scala#L89.

### Marathon API

Note that according to the [Marathon API Docs](http://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-apps-appid-embed-embed) we may need to add `?embed=tasks` soon anyway.

Abridged response for `/v2/apps/[appId]`:
```json
{
  "app": {
    "id": "/toggle",
    "tasks": [
      {
        "appId": "/toggle",
        "healthCheckResults": [
          {
            "alive": true,
            "taskId": "toggle.802df2ae-3ad4-11e4-a400-56847afe9799"
          },
          {
            "alive": true,
            "taskId": "toggle.802df2ae-3ad4-11e4-a400-56847afe9799"
          }
        ],
        "host": "10.141.141.10",
        "id": "toggle.7c99814d-3ad4-11e4-a400-56847afe9799",
        "ports": [
          31234
        ]
      }
    ]
  }
}
```
