### ISSUE TITLE
ensure end-to-end flow control

### ISSUE THREAD

**Issue by olix0r** [BuoyantIO/linkerd#730]
Initial tests show that linkerd does not properly apply flow control across client and server streams.

For flow control to work properly, stream transport writes _must not_ complete until the window is opened. I think that this does not currently behave correctly, so that linkerd blindly reads an entire stream even when the next hop cannot receive it, eventually causing linkerd to OOM.

**Comment by olix0r** [comment]
I have an end-to-end test that verifies that netty's Http2Codec doesn't enforce flow control properly.  Specifically, the write() promise is satisfied before the data is actually written (i.e. when flow control is enforced).  This causes linkerd to call `Frame.Data.release()`, opening inbound flow control prematurely.

When I started digging into the write-completion logic, I found the following in netty's AbstractHttp2StreamChannel:
>         // TODO: this is pretty broken; futures should only be completed after they are processed on
>        // the parent channel. However, it isn't currently possible due to ChannelOutboundBuffer's
>        // behavior which requires completing the current future before getting the next message. It
>        // should become easier once we have outbound flow control support.
>        // https://github.com/netty/netty/issues/4941

We could potentially fix this by using the legacy APIs.  Though, it looks like https://github.com/netty/netty/pull/5914 should just fix this in Netty.  But, we'll have to get this upgrade through Finagle, which, as we know, currently can take a bit of time.

**Comment by buchgr** [comment]
@olix0r 

It's great to hear that you are using Netty's `Http2Codec` :). It's highly experimental. Would love to get some feedback!

> Though, it looks like netty/netty#5914 should just fix this in Netty.

The PR you are talking about does two things in that regard:

1. Promises are only completed once the frames have actually been written. So after they have passed stream and connection level flow control and so on.
2. A child channel's writability changes depending on the available _stream-level_ flow control window. So you will be able to observe that via `ChannelHandler.writabilityChanged`. 

Cheers!

**Comment by olix0r** [comment]
Looking forward to it, @buchgr!

Another question: It seems that `Http2Codec` (I haven't checked where exactly) automatically updates the window when receiving request streams? Is this known behavior? For example:
```
INF [20161017-22:57:05.179] http2: ----------------INBOUND--------------------
INF [20161017-22:57:05.179] http2: [id: 0xae5561fd, L:/192.168.1.187:55378 - R:/192.168.1.187:55379] DATA: streamId=3, padding=0, endStream=false, length=16384, bytes=01010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101...
INF [20161017-22:57:05.179] http2: ------------------------------------
INF [20161017-22:57:05.188] http2: 
INF [20161017-22:57:05.188] http2: ----------------INBOUND--------------------
INF [20161017-22:57:05.188] http2: [id: 0xae5561fd, L:/192.168.1.187:55378 - R:/192.168.1.187:55379] DATA: streamId=3, padding=0, endStream=false, length=16384, bytes=01010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101...
INF [20161017-22:57:05.188] http2: ------------------------------------
INF [20161017-22:57:05.189] http2: 
INF [20161017-22:57:05.189] http2: ----------------OUTBOUND--------------------
INF [20161017-22:57:05.189] http2: [id: 0xae5561fd, L:/192.168.1.187:55378 - R:/192.168.1.187:55379] WINDOW_UPDATE: streamId=0, windowSizeIncrement=32768
INF [20161017-22:57:05.189] http2: ------------------------------------
```
As far as I can tell, Netty is issuing this `WINDOW_UPDATE` on its own. We need to be able to defer this update until the data has been forwarded.

**Comment by ejona86** [comment]
@olix0r the behavior you are seeing is expected. Easiest thing to do is disable AUTO_READ on the child channel when you want to push-back. Anything read is automatically considered "consumed" and returns flow control window. This is effectively the same behavior you would see when using HTTP/1 in Netty.

I was thinking the child channel could have an option that disables the auto return on read. Your handler would then be responsible for sending WINDOW_UPDATEs when you consumed the data. That isn't there today, but it is relatively easy to add. But it's also lower on the priority list since you can already disable AUTO_READ.

**Comment by buchgr** [comment]
@olix0r 

> INF [20161017-22:57:05.189] http2: [id: 0xae5561fd, L:/192.168.1.187:55378 - R:/192.168.1.187:55379] WINDOW_UPDATE: **streamId=0,** windowSizeIncrement=3276

You are seeing a flow control window update for the connection window (stream 0). Yes, Netty will do that automatically and there are currently not plans on changing that.

Furthermore, the child channel will also automatically update the stream-level flow control window after a `channelRead`. If you don't want that, you can turn off `autoRead` [1] on the child channel and thereby apply back pressure (I think that's what you want). 

Essentially, after having read some data you turn auto read off, forward the data and once you are done you turn auto read on again, or call read manually.

Please let me know if that helps or if you have any further questions.

[1] http://netty.io/wiki/new-and-noteworthy-in-4.0.html#sensible-and-less-error-prone-inbound-traffic-suspension

**Comment by olix0r** [comment]
Thanks for the clarification, @buchgr & @ejona86!
