### ISSUE TITLE
add auth support to marathon namer

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/linkerd#743]
# Summary

linkerd's Marathon namer only supports unauthenticated access to the Marathon API. Marathon may be configured to require authentication, and is always the case in DC/OS Enterprise Edition.

We should modify the Marathon namer to read from a `DCOS_SERVICE_ACCOUNT_CREDENTIAL` environment variable. This environment variable contains a private key, giving the Marathon namer access to the DC/OS API.

# DC/OS Setup

This will require the user to create a DC/OS service account and a DC/OS secret, all prior to linkerd deployment. Full details:
https://docs.mesosphere.com/1.8/administration/id-and-access-mgt/service-auth/custom-service-auth/

## Service account and secret creation

```bash
# generate a keypair
openssl genrsa -out private-key.pem 2048
openssl rsa -in private-key.pem -pubout -out public-key.pem

# modify keypair files for use in curl
tr -d '\n' < public-key.pem | tee public-key.pem
cat private-key.pem | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g' > private_key.pem

# create service account
# Note that <PUBLIC-KEY> is the contents of public-key.pem, with "\n" added after "-----BEGIN PUBLIC KEY-----" and before "-----END PUBLIC KEY-----"
curl -X PUT -H "Content-Type: application/json" -H "Authorization: token=$(dcos config show core.dcos_acs_token)" -d "{\"description\":\"linkerd test service\",\"public_key\":\"<PUBLIC-KEY>\"}" $(dcos config show core.dcos_url)/acs/api/v1/users/linkerd-service-acct

# add perms to service account
curl -X PUT -H "Authorization: token=$(dcos config show core.dcos_acs_token)" $(dcos config show core.dcos_url)/acs/api/v1/acls/dcos:superuser/users/linkerd-service-acct/full

# create secret
curl -v -X PUT -H "Content-Type: application/json" -H "Authorization: token=$(dcos config show core.dcos_acs_token)" -d "{\"value\":\"{\\\"scheme\\\": \\\"RS256\\\",\\\"uid\\\": \\\"linkerd-service-acct\\\",\\\"private_key\\\": \\\"$(cat private-key.pem | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g')\\\",\\\"login_endpoint\\\": \\\"https://leader.mesos/acs/api/v1/auth/login\\\"}\"}" $(dcos config show core.dcos_url)/secrets/v1/secret/default/linkerd-secret
```

secret format:
```json
{
  "scheme": "RS256",
  "uid": "service-acct",
  "private_key": "<private-key-value>",
  "login_endpoint": "https://leader.mesos/acs/api/v1/auth/login"
}
```

## linkerd Marathon config
```json
"env": {
  "DCOS_SERVICE_ACCOUNT_CREDENTIAL": { "secret": "serviceCredential" }
},
"secrets": {
  "serviceCredential": {
    "source": "linkerd-secret"
  }
}
```

### JWT Generation

From inside docker/linkerd environment, generate a JWT token

#### Payload:
```json
{"uid": "my-new-service-acct"}
```

```bash
echo "{\"uid\":\"$(echo $DCOS_SERVICE_ACCOUNT_CREDENTIAL | jq --raw-output .uid)\"}"
```

#### Private key
```bash
echo $DCOS_SERVICE_ACCOUNT_CREDENTIAL | jq --raw-output .private_key
```

#### Headers
```json
{
  "alg": "RS256",
  "typ": "JWT"
}
```

#### Login endpoint
```bash
LOGIN_ENDPOINT=$(echo $DCOS_SERVICE_ACCOUNT_CREDENTIAL | jq --raw-output .login_endpoint)
```

Get temporary `DCOS_TOKEN` using `JWT_TOKEN`:
```bash
DCOS_TOKEN=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"uid\":\"$UID\",\"token\":\"$JWT_TOKEN\"}" $LOGIN_ENDPOINT | jq --raw-output .token)
```

### Authenticate

linkerd can now connect to authenticated endpoints:
```bash
curl -H "Authorization: token=$DCOS_TOKEN" leader.mesos/service/marathon/v2/apps
```

# Open Issues

1) Determine how to handle HTTPS. Enabling `SSL_ENABLED` causes a cert failure. The other Universe frameworks set `SSL_CERT_FILE`, `SSL_KEY_FILE`, `SSL_CA_FILE`. `SSL_CA_FILE` seems to be available on mesos leader but not on the agent nodes. More details at https://docs.mesosphere.com/1.8/administration/tls-ssl/#get-dcos-cert.

  ```bash
  $ ls /run/dcos/pki/tls/private/
  bouncer.key  cosmos.key  minuteman.key  navstar.key  networking_api.key

  $ ls /run/dcos/pki/tls/certs
  cosmos.crt  minuteman.crt  navstar.crt  networking_api.crt

  $ ls -R /run/dcos/pki/CA/
  /run/dcos/pki/CA/:
  certs  private
  /run/dcos/pki/CA/certs:
  ca.crt  cacerts.jks
  /run/dcos/pki/CA/private:
  ca.key
  ```

**Comment by olix0r** [comment]
Is it really common practice to provide secrets via environment variables?  As far as I understand, this isn't really safe since users on the parent OS can read these without appropriate access control (i.e. via `ps -E`).

**Comment by siggy** [comment]
This is the recommended process for all DC/OS packages.

code:
https://github.com/mesosphere/universe/search?utf8=%E2%9C%93&q=DCOS_SERVICE_ACCOUNT_CREDENTIAL

docs:
https://docs.mesosphere.com/1.8/administration/id-and-access-mgt/service-auth/universe-service-auth/
https://docs.mesosphere.com/1.8/administration/id-and-access-mgt/service-auth/custom-service-auth/
