### ISSUE TITLE
Expose failure accrual configuration

### ISSUE THREAD

**Issue by OleksandrBerezianskyi** [BuoyantIO/linkerd#763]
From what we see in our tests linkerd's default failure accrual marks destination as dead with the next message:

> I 1020 15:05:15.815 THREAD31 TraceId:42c4a7509ec208dd: FailureAccrualFactory marking connection to "#/io.l5d.fs/rss" as dead. Remote Address: Inet(/172.17.0.1:18081,Map())

Currently linkerd does not expose failure accrual configuration: https://twitter.github.io/finagle/guide/Clients.html#failure-accrual

It would be nice to have failure accrual configuration exposed in linkerd config file

**Comment by adleong** [comment]
This is done!
