### ISSUE TITLE
MVP Acceptance test for linkerd releases

### ISSUE THREAD

**Issue by gtcampbell** [BuoyantIO/linkerd#78]
To verify a new linkerd release, we should ensure that it can successfully load configuration for all supported namers and router protocols, along with an admin configuration (i.e. a "[Christmas tree configuration](https://en.wikipedia.org/wiki/Christmas_tree_packet)").

The next phase would be to implement integration tests for the relevant protocols and service discovery providers.

**Comment by olix0r** [comment]
we have an acceptance test script
