### ISSUE TITLE
Configuration option to disable implicit content gzipping on the linkerd side

### ISSUE THREAD

**Issue by OleksandrBerezianskyi** [BuoyantIO/linkerd#794]
As of 0.8.2 linkerd is gzipping http body if client have sent "Accept-encoding":"gzip,deflate" even if service have not zipped the content. I think linkerd should not decide to gzip the content on behalf of the service as the service knows better. For example it does not seems reasonable to gzip the content with the size less then 2KB.

**Comment by OleksandrBerezianskyi** [comment]
Also this can cause a huge CPU load on the side of linkerd

**Comment by olix0r** [comment]
Ah hah! It appears we already have this.  From the [http protocol config docs](https://linkerd.io/config/0.8.2/linkerd/index.html#client-parameters).  Setting `compressionLevel: 0` on a router should disable compression explicitly.

**Comment by OleksandrBerezianskyi** [comment]
Thanks! _(feeling miserable)_
