### ISSUE TITLE
Improve dtab ergonomics for dropping path segments

### ISSUE THREAD

**Issue by adleong** [BuoyantIO/linkerd#81]
```
/http/1.1 => /method ;
/method => /$/io.buoyant.http.anyMethodPfx/host ;
/host => /$/io.buoyant.http.anyHostPfx/local ;
/local => /$/inet/127.1/8080 ;
```

This is verbose, hard to understand, and hard to maintain.  It would be great if we had some kind of syntactic sugar to make this easier.

```
/http/1.1/*/* => /$/inet/127.1/8080
```

**Comment by olix0r** [comment]
A first attempt of this posted at https://github.com/twitter/finagle/pull/472
