### ISSUE TITLE
linkerd and namerd fail to start when JAVA_HOME contains spaces

### ISSUE THREAD

**Issue by sstock** [BuoyantIO/linkerd#816]
Simple example

    $ export JAVA_HOME="/tmp/space space"
    $ ./linkerd-0.8.3-exec 
    ./linkerd-0.8.3-exec: 25: exec: /tmp/space: not found
    $ ./namerd-0.8.3-exec 
    ./namerd-0.8.3-exec: 25: exec: /tmp/space: not found

Quoting the java executable path corrects the issue: exec "${JAVA_HOME:-/usr}/bin/java" ...

**Comment by adleong** [comment]
Nice find!  PRs welcome :)
