### ISSUE TITLE
Rewriting Namer

### ISSUE THREAD

**Issue by adleong** [BuoyantIO/linkerd#843]
Add a namer that takes an existing name and rewrites it according to a template.  This is inspired by the way that the boundPath client TLS plugin works (https://linkerd.io/config/0.8.3/linkerd/index.html#tls-with-bound-path)

```
kind: io.l5d.rewrite
pattern: /http/*/{method}/{host}
name: /s/{host}/{method}
```

The above config will accept names like `/#/io.l5d.rewrite/http/1.1/GET/foo` and resolve them as `/s/foo/GET`.

1. If the name after the `/#/io.l5d.rewrite` prefix does not match the pattern, resolve to Neg.
2. Otherwise, capture segments of the name into template variables (`GET` into `{method}` and `foo` info `{host}` in the above example).
3. Fill template variables in the `name` field and resolve it.

**Comment by olix0r** [comment]
note: we'd want to explicitly label these namers like:

```yaml
kind: io.l5d.rewrite
label: hostMethod
pattern: ...
name: ...
```

So that we accept names like `/#/hostMethod/...`.

Point is that it's not useful to see `io.l5d.rewrite` in a dtab.

**Comment by adleong** [comment]
@olix0r I think this is already accomplished by the prefix property:

```
kind: io.l5d.rewrite
prefix: /hostMethod
pattern: ...
name: ...
```

do you think that's sufficient?
