### ISSUE TITLE
Add a simple host:port namer with no lookup

### ISSUE THREAD

**Issue by adrian** [BuoyantIO/linkerd#904]
Could I request a namer than maps host:port directly without any external service lookup.

For example,
- bind `/http/1.1/GET/10.2.2.56/16992` to `10.2.2.56:16992`
- bind `/http/1.1/GET/10.2.3.43/17335` to `10.2.3.43:17335`
etc

The reason for this is so that calling apps can do service lookup themselves and leave linkerd to just proxy the URL.

**Comment by wmorgan** [comment]
Thanks, Adrian!

**Comment by adleong** [comment]
I think I may be missing something here.  Could you use a dtab like:
```
/http/*/* => /$/inet
```
which would map `/http/1.1/GET/10.2.2.56/16992` to `/$/inet/10.2.2.56/16992`?

**Comment by adrian** [comment]
@adleong You're absolutely right. That gives me exactly what I need. Thanks very much.

@olix0r Do you still think this issue is worth keeping open? I'm happy with the solution proposed by adleong.

**Comment by adleong** [comment]
When a host with a port is specified in the Host header, it is a single path entry: `/http/1.1/GET/10.2.2.56:16992`.  We need a rewriting namer to split on the the `:` into two path segments.

eg.

```
/srv => /$/inet;
/http/*/* => /$/io.buoaynt.http.hostPortPfx/srv;
```

Which would delegate
```
/http/1.1/GET/10.2.2.56:16992
/$/io.buoyant.http.hostPortPfx/srv/10.2.2.56:16992
/srv/10.2.2.56/16992
/$/inet/10.2.2.56/16992
```

**Comment by adrian** [comment]
Does commit 70502c2 address this issue?

**Comment by olix0r** [comment]
@adrian yeah, these new namers will be present in 0.8.6 (being released now).  Let us know if you have any further questions!
