### ISSUE TITLE
trailing slash appended after param when using io.l5d.path identifier

### ISSUE THREAD

**Issue by strzelecki-maciek** [BuoyantIO/linkerd#910]
When a slash precedes ?foo=bar param another slash is appended as trailing slash to the url.
Example: /foo/bar/?foo=bar is forwarded as /foo/bar/?foo=bar/
This causes problems with parsing the params by upstream service.

**Comment by wmorgan** [comment]
Thanks, Maciej!

**Comment by leozc** [comment]
This would be related to a bug in this fix:
https://github.com/BuoyantIO/linkerd/pull/711/files/0281c61224af19498f212c7b76a8af6ffe1e04b6
