### ISSUE TITLE
Add an option to ConsulNamer to support stripping domains from service names

### ISSUE THREAD

**Issue by akreiling** [BuoyantIO/linkerd#911]
We would like to use the following pattern to facilitate service discovery for our application developers when migrating to our new linkerd mesh. I propose adding an option to `ConsulNamer` to strip extraneous domain information during the Host to Consul service lookup. This would be advantageous by allowing our customers to start using services backed by linkerd via configuration changes without forcing any code/client changes to support the necessary header manipulation.

Here's the idea:

1. Create a wildcard domain record for *.service.local that points to linkerd. (Or one could use dnsmasq trickery)
2. Clients issue HTTP requests to `servicename.service.local`
3. Linkerd's ConsulNamer resolves `servicename.service.local` to the Consul service `servicename`
4. Everybody is happy.

**Comment by olix0r** [comment]
Hi @akreiling! Thanks for filing the issue.

I think this can be accomplished without code change by layering the [`/$/io.buoyant.http.subdomainOfPfx`](https://linkerd.io/config/head/linkerd/index.html#rewriting-namers) namer, for instance:
```
/consul => /#/io.l5d.consul/dc1 ;
/host => /$/io.buoyant.http.subdomainOfPfx/service.local/consul ;
/http/1.1/* => /host ;
```

I think this should Just Work for the situation you describe.

**Comment by akreiling** [comment]
thanks -- this works like a charm.
-a
