### ISSUE TITLE
admin dashboard: sort servers and clients alphabetically

### ISSUE THREAD

**Issue by klingerf** [BuoyantIO/linkerd#915]
I think this is a relatively small change, but it would be great to sort the routers and clients that show up on the admin dashboard alphabetically, so that they load in a consistent order each time. Right now I think it's just hash ordering. Here's an example:

![screen shot 2017-01-10 at 2 19 18 pm](https://cloud.githubusercontent.com/assets/9226/21827529/e80042d4-d740-11e6-94b8-ed5800b5d90c.png)

**Comment by adleong** [comment]
personally I would expect the routers to be displayed in the order that they appear in the config file.

**Comment by klingerf** [comment]
@adleong Makes sense. From an implementation standpoint, all of the labels on the dashboard are derived from the metrics.json response, which is unordered. Seems like we might need to make a separate API call back to the server to fetch router ordering?

**Comment by adleong** [comment]
Sounds like a pain in the butt.  I don't have strong feelings about this if it's too annoying to do.

**Comment by klingerf** [comment]
Turns out routers are already sorted in the order that they are defined in the config file. 🎉  I changed the title of this issue to reflect that.
