### ISSUE TITLE
Investigate which additional linkerd metrics should be displayed on the dashboard

### ISSUE THREAD

**Issue by adleong** [BuoyantIO/linkerd#920]
The linkerd metrics.json is full of very rich and useful data.  We should surface it more on the dashboard.

A few off the top of my head:
* circuit breaker status
* Load balancer pool sizes

**Comment by adleong** [comment]
The following per-client stats should be displayed on the dashboard:

* Load balancer size
* Load balancer available
* Break failures down into individual exception counts
* Retry percentage
* Retry budget

**Comment by klingerf** [comment]
In the failure accrual demo, I'm also displaying the client `removed_for_ms` stat, which tracks total time that instances have been removed from the pool, and that might be useful to surface in the dashboard as well.
